project_id = "ckkfacyqcwoxcgbmxyxy"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54328
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true
enable_signup = true

[edge_runtime]
enabled = true
port = 54329

[functions.create-payment]
verify_jwt = true

[functions.verify-coupon]
verify_jwt = false

[functions.profile-management]
verify_jwt = true

[functions.change-password]
verify_jwt = true

[functions.user-orders]
verify_jwt = true

[functions.search]
verify_jwt = false

[functions.course-management]
verify_jwt = false

[functions.test-management]
verify_jwt = false

[functions.analytics]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false

[functions.create-razorpay-payment]
verify_jwt = true

[functions.verify-razorpay-payment]
verify_jwt = true